language: elixir

sudo: required
dist: trusty

elixir:
  - 1.6

addons:
    postgresql: "9.6"
services:
    - postgresql

env:
  - MIX_ENV=test DATABASE_URL=ecto://postgres:postgres@postgres/krypton_test

script:
  - mix test && mix coveralls.travis
