language: elixir

sudo: required
dist: trusty

elixir:
  - 1.6

addons:
    postgresql: "9.6"
services:
    - postgresql

env:
  global:
    - MIX_ENV=test
    - DB_USERNAME=postgres
    - DB_PASSWORD=postgres
    - DB_NAME=krypton_test
    - DB_HOST=localhost

before_script:
  - mix do deps.get, ecto.create, ecto.migrate

script:
  - mix test && mix coveralls.travis

after_script:
  - mix inch.report
