version: '3'

services:
  web:
    image: docker.io/zverseckas/krypton
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=krypton_dev
      - DB_HOST=postgres
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    links:
      - postgres

  postgres:
    image: postgres:10.3
    ports:
      - "5432:5432"
